### ISSUE TITLE
Build AprilTag detection script for RPi

### ISSUE THREAD

**Issue by CJKeller03** [Stellar-Robotics/Robot-Code-2024#3]
Detailed guide on setting up the Raspberry Pi and getting AprilTag detection running.
[https://docs.wpilib.org/en/stable/docs/software/vision-processing/wpilibpi/using-the-raspberry-pi-for-frc.html](https://docs.wpilib.org/en/stable/docs/software/vision-processing/wpilibpi/using-the-raspberry-pi-for-frc.html)

Please use Python for the vision script running on the pi.

- [x] Flash the WPILib Rasperry Pi image onto the SD card and boot the pi using it.
- [x] Write a basic Python script to grab images from a USB-connected camera.
- [x] Use the AprilTag library to detect AprilTags in the image, and display their position to the user in whatever way is easiest.

**Comment by AbstractestThought** [comment]
It looks like that guide is actually for vision tracking with reflective tape, but I’m sure we can scavenge some information from it.
Here is the documentation for the AprilTag package for easier reference: https://robotpy.readthedocs.io/projects/robotpy/en/stable/robotpy_apriltag.html

**Comment by CJKeller03** [comment]
There is information about detecting AprilTags in there, but you're right - it's not well-organized and kind of difficult to find. The link I sent starts with the RPi setup, but here's a direct link to the section about AprilTags if you need any more usage context! [https://docs.wpilib.org/en/stable/docs/software/vision-processing/apriltag/apriltag-intro.html#software-support](https://docs.wpilib.org/en/stable/docs/software/vision-processing/apriltag/apriltag-intro.html#software-support)
